### ISSUE TITLE
Unable to get correct image path

### ISSUE THREAD

**Issue by yara-tle** [teambit/react-tailwind-env#8]
When importing images in a component the extension are not able to resolve correct path to the image.
This with regular imports e.g

`import logo from './images/logo.png';`

`<img src={logo} alt="yara logo" width="50" height="50" />`

**Comment by yara-tle** [comment]
After deleting node_modules and reinstall, it seems like this example is missing @tembit/webpack package.
Can't see the dependency in workspace either.

**Comment by yara-tle** [comment]
Seems like the filename gets hashed, but no image.

<img width="684" alt="Screenshot 2021-08-08 at 13 47 09" src="https://user-images.githubusercontent.com/83707900/128630924-cabf9d34-9232-42b0-a3b3-37a820d7e115.png">

**Comment by yara-tle** [comment]
This is also a problem in the plain` teambit.react/react` extension.

**Comment by GiladShoham** [comment]
If it's a problem with the plain react extension, better to open the issue on the main https://github.com/teambit/bit repo
